# Generated by Django 4.2.9 on 2024-02-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
