# Generated by Django 4.2.9 on 2024-02-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
