# Generated by Django 4.2.9 on 2024-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deliver', 'Delivered'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='In Review', max_length=10),
        ),
    ]
