# Generated by Django 4.2.9 on 2024-02-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contactus_subject_contactus_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_choice',
            field=models.CharField(choices=[('draft', 'Draft'), ('deliver', 'Delivered'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='In Review', max_length=10),
        ),
    ]
