# Generated by Django 5.0.2 on 2024-02-25 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_options_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='total',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
            preserve_default=False,
        ),
    ]
